apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: metrics-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
      - name: cloudflared
        image: cloudflare/cloudflared:2023.5.1
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "500Mi"
        imagePullPolicy: Always
        args: ["tunnel", "--no-autoupdate", "run", "--token=$(TOKEN)"]
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflared-token
                key: token
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudflared
  name: cloudflared-metrics-service
  namespace: cloudflare
spec:
  ports:
  - port: 9100
    targetPort: 9100
  selector:
    app: cloudflared
