apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-streaming
  namespace: api-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-streaming
  template:
    metadata:
      labels:
        app: api-streaming
    spec:
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-pv1
      containers:
        - name: api-streaming
          image: pcisnerp/python-hello-app-for-prod:0.10.0
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: nfs-volume
              mountPath: /mnt/nfs
              
---
apiVersion: v1
kind: Service
metadata:
  name: api-streaming
  namespace: api-streaming
spec:
  selector:
    app: api-streaming
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
---
