apiVersion: v1
kind: Namespace
metadata:
  name: api-streaming
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-streaming
  namespace: api-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-streaming
  template:
    metadata:
      labels:
        app: api-streaming
    spec:
      containers:
        - name: api-streaming
          image: pcisnerp/streaming_api_flask:0.9.0
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-streaming
  namespace: api-streaming
spec:
  selector:
    app: api-streaming
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
