name: Push Docker Image w Tag

on:
  push:
    branches: [ master ]
    paths:
      - 'app_api_streaming/app/**' # This filters changes in the "app/" folder

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  CONTAINER_NAME: python-hello-app-for-prod
  IMAGE_TAG: latest

jobs:
  push:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: ""

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_USERNAME/$CONTAINER_NAME:${{ steps.release.outputs.tag_name }} .
          docker push $DOCKER_USERNAME/$CONTAINER_NAME:${{ steps.release.outputs.tag_name }}
          docker build -t $DOCKER_USERNAME/$CONTAINER_NAME:$IMAGE_TAG .
          docker push $DOCKER_USERNAME/$CONTAINER_NAME:$IMAGE_TAG

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.release.outputs.upload_url }}"