name: Push Docker Image w Tag

on:
  push:
    branches: [ master ]
    paths:
      - 'app_api_streaming/app/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  CONTAINER_NAME: streaming_api_flask
  IMAGE_TAG: latest

jobs:
  push:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: ""

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push Docker image with release tag
        run: |
          docker build -t $DOCKER_USERNAME/$CONTAINER_NAME:${{ steps.release.outputs.tag_name }} .
          docker push $DOCKER_USERNAME/$CONTAINER_NAME:${{ steps.release.outputs.tag_name }}
        working-directory: app_api_streaming

      # Trivy vulnerability scanner
      - name: Run Trivy vulnerability scanner on release tag
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.DOCKER_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ steps.release.outputs.tag_name }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build and push Docker image with 'latest' tag
        run: |
          docker build -t $DOCKER_USERNAME/$CONTAINER_NAME:$IMAGE_TAG -f Dockerfile .
          docker push $DOCKER_USERNAME/$CONTAINER_NAME:$IMAGE_TAG
        working-directory: app_api_streaming

      # Trivy vulnerability scanner
      - name: Run Trivy vulnerability scanner on latest tag
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $DOCKER_USERNAME/$CONTAINER_NAME:$IMAGE_TAG
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Log out of Docker Hub
        if: always()
        run: docker logout

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.release.outputs.upload_url }}"
