name: OWASP Dependency-Check

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PROJECT_NAME: streaming_api_flask
  SCAN_PATH: app_api_streaming/app

jobs:
  dependency_check:
    name: OWASP Dependency Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin' # This can be 'adopt', 'temurin', 'zulu', etc.
      
      - name: Print JAVA_HOME
        run: echo "JAVA_HOME=${JAVA_HOME}"

      - name: OWASP Dependency-install
        run: |
          # Install OWASP Dependency-Check
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.3.1/dependency-check-6.3.1-release.zip
          unzip dependency-check-6.3.1-release.zip -d dependency-check
          sudo chmod +x dependency-check/dependency-check/bin/dependency-check.sh
          echo "$(pwd)/dependency-check/dependency-check/bin" >> $GITHUB_PATH

      - name: OWASP Dependency-Check
        run: |
          # Ensure the dependency-check.sh is executable
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh
        env:
          # Ensure JAVA_HOME is passed as an environment variable
          JAVA_HOME: ${{ env.JAVA_HOME }}
        
      - name: OWASP Dependency-Run
        run: |
          # Run OWASP Dependency-Check on your project
          sh dependency-check/dependency-check/bin/dependency-check.sh --project "$PROJECT_NAME" --scan ${{ env.SCAN_PATH }} --out . --format HTML

      - name: Update OWASP Badge
        if: always()
        run: |
          OWASP_STATUS="failed"
          if [ "${{ job.status }}" == 'success' ]; then
              OWASP_STATUS="passing"
          fi
          sed -i "s/OWASP Status: .*/OWASP Status: ${OWASP_STATUS}/" README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update OWASP status"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PS_TOKEN }}
