name: trivy scanfs

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy vulnerability scanner
        run: |
          trivy fs --format table --exit-code 1 --ignore-unfixed --vuln-type os,library --severity CRITICAL,HIGH .